import { beforeAll,afterAll,it,expect } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
const db=new PGlite();
const admin='11111111-1111-4111-8111-111111111111', visitor='22222222-2222-4222-8222-222222222222';
beforeAll(async()=>{await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated; insert into auth.users values ('${admin}'),('${visitor}');`);await db.exec(fs.readFileSync('supabase/migrations/202610020001_archive.sql','utf8'));await db.exec(`insert into private.administrators values('${admin}')`);});
afterAll(async()=>await db.close());
async function as(role:string,id:string=''){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${role}`);}
async function save(kind:string,payload:any,stamp:string|null=null){return db.query('select public.save_record($1,$2::jsonb,$3::timestamptz,$4)',[kind,JSON.stringify(payload),stamp,'Test change']);}
it('anonymous cannot read raw records or audit, or write',async()=>{await as('anon');await expect(db.query('select * from public.members')).rejects.toThrow(/permission denied/);await expect(db.query('select * from public.audit_log')).rejects.toThrow(/permission denied/);await expect(save('clans',{id:'bad',name:'Bad',kind:'Yautja clan'})).rejects.toThrow(/permission denied/);expect((await db.query('select public.public_archive() as data')).rows[0]).toHaveProperty('data.members',[]);});
it('ordinary authenticated users cannot read private data or write',async()=>{await as('authenticated',visitor);expect((await db.query('select * from public.members')).rows).toEqual([]);expect((await db.query('select * from public.audit_log')).rows).toEqual([]);await expect(save('clans',{id:'bad',name:'Bad',kind:'Yautja clan'})).rejects.toThrow(/Administrator approval/);await expect(db.query(`insert into private.administrators values('${visitor}')`)).rejects.toThrow(/permission denied/);});
it('approved admin saves, audit records reason, and draft stays private',async()=>{await as('authenticated',admin);await save('members',{id:'m',name:'Test hunter',rank:'Blooded',status:'Active',player:'private-handle'});const records=await db.query('select * from public.members');expect(records.rows).toHaveLength(1);expect((await db.query('select reason from public.audit_log')).rows[0]).toEqual({reason:'Test change'});await as('anon');expect((await db.query<any>('select public.public_archive() as data')).rows[0].data.members).toEqual([]);});
it('published projection withholds metadata and non-public player handles',async()=>{await as('authenticated',admin);const row=(await db.query<any>('select * from public.members')).rows[0];await save('members',{...row,published:true},row.updated_at.toISOString());await as('anon');const row2=(await db.query<any>('select public.public_archive() as data')).rows[0].data.members[0];expect(row2.name).toBe('Test hunter');expect(row2).not.toHaveProperty('player');expect(row2).not.toHaveProperty('updated_at');});
it('rejects stale edits instead of losing a prior save',async()=>{await as('authenticated',admin);await expect(save('members',{id:'m',name:'Lost update',rank:'Blooded',status:'Active'})).rejects.toThrow(/changed since/);});
it('atomic cyclic import preserves dates and is idempotent',async()=>{await as('authenticated',admin);const fixture={members:[{id:'legacy-member',name:'Legacy hunter',house:'legacy-house',rank:'Ancient',status:'Active',created_at:'2020-01-01T00:00:00Z',updated_at:'2020-01-02T00:00:00Z'}],houses:[{id:'legacy-house',name:'Legacy house',senior:'legacy-member',status:'Active'}]};const first=await db.query<any>('select public.import_archive($1) as counts',[JSON.stringify(fixture)]);expect(first.rows[0].counts.members).toBe(1);const second=await db.query<any>('select public.import_archive($1) as counts',[JSON.stringify(fixture)]);expect(second.rows[0].counts.members).toBe(0);expect((await db.query<any>("select created_at from public.members where id='legacy-member'")).rows[0].created_at.toISOString()).toBe('2020-01-01T00:00:00.000Z');});
it('invalid imports roll back completely',async()=>{await as('authenticated',admin);await expect(db.query('select public.import_archive($1)',[JSON.stringify({members:[{id:'invalid-ref',name:'Bad',rank:'Blooded',status:'Active',house:'absent'}]})])).rejects.toThrow(/foreign key/);expect((await db.query("select * from public.members where id='invalid-ref'")).rows).toHaveLength(0);});
