import { useEffect, useState, type FormEvent } from 'react';
import { client, exportBackup, forumConfigure, forumThreads, listAccounts, loadData, reviewAccount, saveRecord, supersedeRelation, type AccountRow } from './service';
import { active, emptyData, kinds, schemas, validate, type Dataset, type Kind, type RecordData } from './model';
import { FieldInput } from './Fields';
const newId=(kind:Kind)=>`${schemas[kind].prefix}-${crypto.randomUUID()}`;
export function Admin({onChanged}:{onChanged:()=>void}){
 const [access,setAccess]=useState<'checking'|'signed-out'|'denied'|'admin'>('checking'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[data,setData]=useState<Dataset>(emptyData),[kind,setKind]=useState<Kind>('members'),[row,setRow]=useState<RecordData|null>(null),[replacing,setReplacing]=useState<RecordData|null>(null),[reason,setReason]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{if(!client)return;let alive=true;let generation=0;const check=async()=>{const current=++generation;setAccess('checking');setData(emptyData());setRow(null);try{const {data:{session},error:sessionError}=await client!.auth.getSession();if(sessionError)throw sessionError;if(!session){if(alive&&current===generation)setAccess('signed-out');return;}const {data:allowed,error}=await client!.rpc('is_admin');if(error)throw error;if(!allowed){if(alive&&current===generation)setAccess('denied');return;}const records=await loadData(true);if(alive&&current===generation){setData(records);setAccess('admin');}}catch(e){if(alive){setError((e as Error).message);setAccess('denied');}}};void check();const {data:listener}=client.auth.onAuthStateChange(()=>{setTimeout(()=>void check(),0);});return()=>{alive=false;listener.subscription.unsubscribe();};},[]);
 async function signIn(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const {error}=await client!.auth.signInWithPassword({email,password});if(error)throw error;setPassword('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function open(next:RecordData|null,old:RecordData|null=null){setRow(next);setReplacing(old);setReason('');setError('');setMessage('');}
 async function save(e:FormEvent){e.preventDefault();if(!row||busy)return;setError('');setMessage('');
  // While superseding, the old assessment is archived in the same transaction, so it does not count as a duplicate direction.
  const errors=validate(kind,row,replacing?{...data,relations:data.relations.filter(r=>r.id!==replacing.id)}:data);if(!reason.trim())errors.push('A change reason is required.');if(errors.length){setError(errors.join('\n'));return;}
  setBusy(true);try{if(replacing)await supersedeRelation(replacing,row,reason);else await saveRecord(kind,row,reason);open(null);setMessage(replacing?'New assessment saved. The earlier one is archived and still shown in its history.':'Record saved.');onChanged();setData(await loadData(true));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function backup(){setBusy(true);setError('');try{const payload=await exportBackup();const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`tjauke-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!client)return <section className="panel setup"><h2>Administrator access is not configured</h2><p>The public preview uses a local workbook snapshot. Saving requires a Supabase project and an approved administrator account.</p><ol><li>Create a Supabase project.</li><li>Apply the database migrations supplied with this repository.</li><li>Create your administrator account and add its user ID to the administrator allowlist.</li><li>Set the project URL and public publishable key in the local environment.</li></ol><p>The repository README contains the setup commands.</p></section>;
 const existing=row&&data[kind].some(r=>r.id===row.id);
 return <>{error&&<p className="notice error prose" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}{access==='checking'?<p role="status">Checking administrator access…</p>:access==='signed-out'?<form className="panel login" onSubmit={signIn}><h2>Administrator sign-in</h2><p>Access is limited to approved administrators. Hunters sign in from <a href="#/account">their account page</a>.</p><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form>:access==='denied'?<section className="panel"><h2>Administrator approval required</h2><p>This account does not have access to administration. <a href="#/account">Go to your hunter account</a>.</p><button onClick={()=>void client!.auth.signOut()}>Sign out</button></section>:<>
  <div className="admin-toolbar"><label>Record type<select value={kind} disabled={busy} onChange={e=>{setKind(e.target.value as Kind);open(null);}}>{kinds.map(k=><option key={k} value={k}>{schemas[k].title}</option>)}</select></label><button disabled={busy} onClick={()=>open({id:newId(kind),archived:false,published:false})}>Add record</button><button disabled={busy} onClick={()=>void backup()}>Export backup</button><button disabled={busy} onClick={()=>void client!.auth.signOut()}>Sign out</button></div>
  <div className="admin-grid"><section className="panel"><h2>{schemas[kind].title}</h2><ul className="record-list">{data[kind].map(r=><li key={r.id}><button className="text-button" disabled={busy} onClick={()=>open({...r})}>{r.name}<small>{r.archived?'Archived':r.published?'Published':'Draft'}</small></button></li>)}</ul>{!data[kind].length&&<p>No records yet.</p>}</section>
  {row?<form className="panel editor" onSubmit={save}><h2>{replacing?'New assessment':existing?'Edit record':'New record'}</h2>{replacing&&<p className="section-note">Replaces “{replacing.name}”. The earlier assessment is archived and stays in this direction’s history.</p>}<p className="record-id">{row.id}</p>
   {kind==='relations'&&existing&&!row.archived&&!replacing&&<p><button type="button" disabled={busy} onClick={()=>open({id:newId('relations'),archived:false,published:row.published,name:'',from:row.from,to:row.to,stance:'',assessed:new Date().toISOString().slice(0,10)},data.relations.find(r=>r.id===row.id)!)}>Record a new assessment</button> <small>Use this when the stance changes, so the old one is kept.</small></p>}
   <fieldset disabled={busy}>{schemas[kind].fields.map(f=><FieldInput key={f.key} field={f} row={row} setRow={setRow} data={data}/>)}{kind==='members'&&<label className="checkbox"><input type="checkbox" checked={row.player_public===true} onChange={e=>setRow({...row,player_public:e.target.checked})}/>Publish this player handle</label>}<label className="checkbox"><input type="checkbox" checked={row.published} onChange={e=>setRow({...row,published:e.target.checked})}/>Published</label>{!replacing&&<label className="checkbox"><input type="checkbox" checked={row.archived} onChange={e=>setRow({...row,archived:e.target.checked})}/>Archived (retains relationships)</label>}<label>Change reason *<textarea rows={2} required value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="form-actions"><button className="primary" type="submit">{busy?'Saving…':replacing?'Save new assessment':'Save record'}</button><button type="button" onClick={()=>open(null)}>Cancel</button></div></fieldset></form>
  :<section className="panel"><p>Select a record to edit, or add a new record.</p></section>}</div>
  <Accounts members={data.members}/>
  <ForumSettings/>
 </>}</>;
}
const statusLabel={pending:'Waiting for approval',approved:'Approved',rejected:'Rejected',suspended:'Suspended'};
/** Account approval and hunter links. Accounts are shown by username; emails are never loaded. */
function Accounts({members}:{members:RecordData[]}){
 const [accounts,setAccounts]=useState<AccountRow[]|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[links,setLinks]=useState<Record<string,string>>({});
 const refresh=async()=>{try{const rows=await listAccounts();setAccounts(rows);setLinks(Object.fromEntries(rows.map(r=>[r.id,r.member||r.requested||''])));}catch(e){setError((e as Error).message);}};
 useEffect(()=>{void refresh();},[]);
 const name=(id:string|null)=>id?members.find(m=>m.id===id)?.name||id:null;
 const label=(a:AccountRow)=>a.username||`Account without username (registered ${a.created_at.slice(0,10)})`;
 async function decide(a:AccountRow,decision:'approved'|'rejected'|'suspended',done:string){if(busy)return;setBusy(true);setError('');setMessage('');try{await reviewAccount(a.id,decision,decision==='approved'?links[a.id]||null:null);setMessage(done);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const hunterSelect=(a:AccountRow)=><label className="inline-select">Hunter<select value={links[a.id]||''} onChange={e=>setLinks({...links,[a.id]:e.target.value})}><option value="">Not linked</option>{active(members).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>;
 const pending=accounts?.filter(a=>a.status==='pending')||[],approved=accounts?.filter(a=>a.status==='approved')||[],closed=accounts?.filter(a=>a.status==='rejected'||a.status==='suspended')||[];
 return <section className="panel accounts"><h2>Accounts</h2>
  <p className="section-note">New registrations wait here. A linked hunter can edit their own profile and declare undertakings; household seniors and Elder rank and above also judge undertakings. Emails are not shown here.</p>
  {error&&<p className="notice error prose" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
  {accounts===null?!error&&<p role="status">Loading accounts…</p>:<fieldset disabled={busy} className="account-groups">
   <h3>Waiting for approval ({pending.length})</h3>
   {pending.length?<ul className="record-list">{pending.map(a=><li key={a.id}><div><span className="record-title">{label(a)}</span><small>Registered {a.created_at.slice(0,10)}{a.requested&&<> · says they play {name(a.requested)}</>}</small>{a.note&&<p className="prose">{a.note}</p>}</div><div className="account-actions">{hunterSelect(a)}<button className="primary" onClick={()=>void decide(a,'approved',`${label(a)} approved.`)}>Approve</button><button onClick={()=>void decide(a,'rejected',`${label(a)} rejected.`)}>Reject</button></div></li>)}</ul>:<p className="empty">No registrations waiting.</p>}
   <h3>Approved ({approved.length})</h3>
   {approved.length?<ul className="record-list">{approved.map(a=><li key={a.id}><div><span className="record-title">{label(a)}</span><small>{a.admin?'Administrator':'Member'}{a.member?<> · linked to {name(a.member)}</>:' · no hunter linked'}</small></div>{!a.admin&&<div className="account-actions">{hunterSelect(a)}<button disabled={(links[a.id]||'')===(a.member||'')} onClick={()=>void decide(a,'approved',links[a.id]?`${label(a)} is linked to ${name(links[a.id])}.`:`${label(a)} is no longer linked to a hunter.`)}>Save link</button><button onClick={()=>void decide(a,'suspended',`${label(a)} suspended.`)}>Suspend</button></div>}</li>)}</ul>:<p className="empty">No approved accounts.</p>}
   {closed.length>0&&<><h3>Rejected or suspended ({closed.length})</h3><ul className="record-list">{closed.map(a=><li key={a.id}><div><span className="record-title">{label(a)}</span><small>{statusLabel[a.status]}</small></div><button onClick={()=>void decide(a,'approved',`${label(a)} reinstated.`)}>Reinstate</button></li>)}</ul></>}
  </fieldset>}
 </section>;
}
function ForumSettings(){
 const [values,setValues]=useState<{days:string;cap:string}|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{forumThreads().then(f=>setValues({days:String(f.settings.retention_days),cap:String(f.settings.thread_cap)})).catch(e=>setError((e as Error).message));},[]);
 async function save(e:FormEvent){e.preventDefault();if(!values||busy)return;setBusy(true);setError('');setMessage('');try{await forumConfigure(Number(values.days),Number(values.cap));setMessage('Forum limits saved. Messages outside the new limits were deleted.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="panel accounts" onSubmit={save}><h2>Forum limits</h2><p className="section-note">Messages older than the retention period are deleted, and each thread keeps only its newest messages up to the limit. Lowering either deletes messages straight away.</p>
  {error&&<p className="notice error prose" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
  {values?<fieldset disabled={busy} className="link-account"><label>Keep messages for (days)<input type="number" min={1} max={365} required value={values.days} onChange={e=>setValues({...values,days:e.target.value})}/></label><label>Messages kept per thread<input type="number" min={5} max={5000} required value={values.cap} onChange={e=>setValues({...values,cap:e.target.value})}/></label><button className="primary">{busy?'Saving…':'Save limits'}</button></fieldset>:!error&&<p role="status">Loading forum limits…</p>}
 </form>;
}
