import { useEffect, useState, type ReactNode } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { active, assessmentHistory, asymmetries, currentRelation, emptyData, kinds, normalize, openHunts, ordered, safeUrl, schemas, type Dataset, type Kind, type RecordData } from './model';
import { client, loadData, localPreview } from './service';
import { Admin } from './Admin';
import { Account } from './Account';
import { Search } from './Search';
import { EvidenceKey, HouseRanks, HuntOutcomes, Lineage, RankTrack, ServiceRecord, Timeline, href } from './Visuals';
const navigation=[['dashboard','Overview'],['members','Hunters'],['houses','Households'],['hunts','Undertakings'],['chronicle','History'],['duties','Duties'],['politics','Politics'],['library','Documents'],['glossary','Glossary']] as const;
const plural=(n:number,one:string,many:string)=>`${n} ${n===1?one:many}`;
const slug=(v:unknown)=>String(v||'').toLowerCase().replace(/[^a-z]+/g,'-');
export function External({url,children}:{url:unknown;children:ReactNode}){const safe=safeUrl(url);return safe?<a className="external" href={safe} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={14} aria-label="opens in a new tab"/></a>:<span>{children} <small>(link unavailable)</small></span>;}
function Mark(){return <svg className="mark" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="4.6" r="2.4"/><circle cx="5.2" cy="17.4" r="2.4"/><circle cx="18.9" cy="16.8" r="2.4"/></svg>;}
export function App(){
 const [route,setRoute]=useState(location.hash.slice(2)||'dashboard'),[data,setData]=useState<Dataset>(emptyData),[status,setStatus]=useState('loading'),[error,setError]=useState(''),[mobile,setMobile]=useState(false),[refresh,setRefresh]=useState(0),[signedIn,setSignedIn]=useState(false);
 const [section,id]=route.split('/');
 useEffect(()=>{const update=()=>{setRoute(location.hash.slice(2)||'dashboard');setMobile(false);window.scrollTo(0,0);};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
 useEffect(()=>{let current=true;setStatus('loading');loadData().then(d=>{if(current){setData(d);setStatus('ready');}}).catch(e=>{if(current){setError(e.message);setStatus('error');}});return()=>{current=false;};},[refresh]);
 useEffect(()=>{const reload=()=>setRefresh(n=>n+1);window.addEventListener('focus',reload);return()=>window.removeEventListener('focus',reload);},[]);
 useEffect(()=>{if(!client)return;void client.auth.getSession().then(({data})=>setSignedIn(!!data.session));const {data:listener}=client.auth.onAuthStateChange((_,session)=>setSignedIn(!!session));return()=>listener.subscription.unsubscribe();},[]);
 // Printed pages show every history entry in full.
 useEffect(()=>{const expand=()=>document.querySelectorAll('details').forEach(d=>d.open=true);window.addEventListener('beforeprint',expand);return()=>window.removeEventListener('beforeprint',expand);},[]);
 const title=navigation.find(n=>n[0]===section)?.[1]||schemas[section as Kind]?.title||(section==='admin'?'Administration':section==='account'?'Your account':'Page not found');
 const settings=active(data.settings)[0];
 return <><a className="skip" href="#main">Skip to content</a><header className="topbar"><a className="brand" href={href('dashboard')}><Mark/><span>Tjau’ke<small>Clan archive</small></span></a><div className="top-actions"><Search data={data} ready={status==='ready'}/>{settings?.rulesUrl&&<External url={settings.rulesUrl}>Honour code</External>}<a className="admin-link" aria-current={section==='account'||section==='admin'?'page':undefined} href={href('account')}>{signedIn?'Your account':'Sign in'}</a><button className="menu" aria-expanded={mobile} aria-controls="sections" onClick={()=>setMobile(!mobile)}>{mobile?'Close':'Menu'}</button></div></header><div className="layout"><aside id="sections" className={mobile?'sidebar open':'sidebar'}><nav aria-label="Archive sections">{navigation.map(([key,label])=><a key={key} aria-current={section===key?'page':undefined} href={href(key)}>{label}{status==='ready'&&key!=='dashboard'&&<span>{active(data[key==='politics'?'clans':key]).length}</span>}</a>)}</nav></aside><div className="content"><main id="main" tabIndex={-1}><h1>{title}</h1>{localPreview&&!client&&<div className="notice">Local preview of the workbook snapshot read on 2 October 2026. Changes are not saved and player handles are withheld.</div>}
 {section==='admin'?<Admin onChanged={()=>setRefresh(n=>n+1)}/>:section==='account'?<Account data={data} onChanged={()=>setRefresh(n=>n+1)}/>:status==='loading'?<div className="state" role="status">Loading clan records…</div>:status==='error'?<div className="state error" role="alert"><h2>Records unavailable</h2><p>{error}</p><button onClick={()=>setRefresh(n=>n+1)}>Try again</button></div>:id&&kinds.includes(section as Kind)?<RecordView kind={section as Kind} id={decodeURIComponent(id)} data={data}/>:section==='dashboard'?<Dashboard data={data}/>:section==='politics'?<Politics data={data}/>:section==='glossary'?<Glossary data={data}/>:kinds.includes(section as Kind)?<Collection key={section} kind={section as Kind} data={data}/>:<div className="state">This page does not exist. <a href={href('dashboard')}>Back to the overview</a></div>}
 </main><footer>Tjau’ke clan archive, a Colonial Marines Universe community project</footer></div></div></>;
}
function Ref({kind,id,data}:{kind:Kind;id:unknown;data:Dataset}){if(!id)return <span className="muted">Not recorded</span>;const r=data[kind].find(r=>r.id===id);return r?<a href={href(kind,r.id)}>{r.name}{r.archived?' (archived)':''}</a>:<span className="muted">Missing reference: {String(id)}</span>;}
function Section({title,to,link,children,className=''}:{title:string;to?:string;link?:string;children:ReactNode;className?:string}){return <section className={`section ${className}`}><div className="section-heading"><h2>{title}</h2>{to&&<a href={href(to)}>{link}</a>}</div>{children}</section>;}
function Empty({children='No records yet.'}:{children?:ReactNode}){return <p className="empty">{children}</p>;}
function RecordList({kind,rows,data}:{kind:Kind;rows:RecordData[];data:Dataset}){return rows.length?<ul className="record-list">{rows.map(r=><li key={r.id}><div><a className="record-title" href={href(kind,r.id)}>{r.name}</a><small>{kind==='hunts'||kind==='promotions'?<Ref kind="members" id={kind==='hunts'?r.hunter:r.member} data={data}/>:String(r.era||r.category||r.meaning||r.mandate||'')}</small></div>{(r.state||r.certainty||r.status||r.rank)&&<span className="tag">{String(r.state||r.certainty||r.status||r.rank)}</span>}</li>)}</ul>:<Empty/>;}
function Roster({rows,data}:{rows:RecordData[];data:Dataset}){return rows.length?<div className="table-scroll"><table className="roster"><thead><tr><th>Hunter</th><th>Rank</th><th>Household</th><th>Standing</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><th scope="row"><a href={href('members',r.id)}>{r.name}</a>{r.player&&<small>{r.player}</small>}</th><td>{r.rank||<span className="muted">Not recorded</span>}</td><td><Ref kind="houses" id={r.house} data={data}/></td><td>{r.status||<span className="muted">Not recorded</span>}</td></tr>)}</tbody></table></div>:<Empty>No hunters recorded.</Empty>;}
function Dashboard({data}:{data:Dataset}){
 const members=active(data.members),houses=active(data.houses),hunts=openHunts(data.hunts),history=active(data.chronicle),docs=active(data.library),duties=active(data.duties).filter(r=>['Active','Acting'].includes(String(r.status))&&!r.end);
 return <><p className="summary">{plural(members.length,'hunter','hunters')} across {plural(houses.length,'household','households')}. {hunts.length?plural(hunts.length,'undertaking is','undertakings are')+' open.':'No undertakings are open.'}</p><div className="overview"><div className="overview-main"><Section title="Hunters" to="members" link={members.length>6?`Full roster (${members.length})`:'Full roster'}><Roster rows={members.slice(0,6)} data={data}/></Section><Section title="Households by rank" to="houses" link="All households"><HouseRanks data={data}/></Section><Section title="History" to="chronicle" link="All history"><RecordList kind="chronicle" rows={ordered(history).slice(0,4)} data={data}/></Section></div><div className="overview-side"><Section title="Open undertakings" to="hunts" link="All undertakings">{hunts.length?<RecordList kind="hunts" rows={hunts} data={data}/>:<Empty>No open undertakings.</Empty>}</Section><Section title="Current duties" to="duties" link="All duties">{duties.length?<ul className="record-list compact">{duties.map(r=><li key={r.id}><a href={href('duties',r.id)}>{r.name}</a><Ref kind="members" id={r.member} data={data}/></li>)}</ul>:<Empty>No current appointments.</Empty>}</Section><Section title="Documents" to="library" link="All documents"><DocumentList rows={ordered(docs).slice(0,5)}/></Section></div></div></>;
}
function DocumentList({rows}:{rows:RecordData[]}){return rows.length?<ul className="record-list">{rows.map(r=><li key={r.id}><div><External url={r.url}>{r.name}</External><small>{r.category}{r.category?' · ':''}<a href={href('library',r.id)}>Details</a></small>{r.summary&&<p>{r.summary}</p>}</div></li>)}</ul>:<Empty>No documents on this shelf.</Empty>;}
function Collection({kind,data}:{kind:Kind;data:Dataset}){const [query,setQuery]=useState(''),[archived,setArchived]=useState(false),[filter,setFilter]=useState('');const filterKey=kind==='library'?'category':kind==='hunts'?'state':kind==='members'?'rank':'';const rows=ordered(data[kind].filter(r=>(archived||!r.archived)&&String(r.name).toLowerCase().includes(query.toLowerCase())&&(!filter||r[filterKey]===filter)));return <>{kind==='hunts'&&<Section title="By household and state"><HuntOutcomes data={data}/></Section>}<div className="filters"><label>Search {schemas[kind].title.toLowerCase()}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name"/></label>{filterKey&&<label>{kind==='library'?'Shelf':kind==='hunts'?'State':'Rank'}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All</option>{[...new Set(data[kind].map(r=>String(r[filterKey]||'')).filter(Boolean))].sort().map(v=><option key={v}>{v}</option>)}</select></label>}<label className="checkbox"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Include archived</label></div><section className="section">{kind==='members'?<Roster rows={rows} data={data}/>:kind==='library'?<DocumentList rows={rows}/>:kind==='chronicle'?rows.length?<><EvidenceKey/><Timeline rows={rows}/></>:<Empty>No history entries match.</Empty>:<RecordList kind={kind} rows={rows} data={data}/>}</section>{kind==='members'&&<Section title="Sponsorship"><p className="section-note">Who sponsored whom. Hunters without a recorded sponsor start a line.</p><Lineage data={data}/></Section>}</>;}
// On a hunter profile these kinds appear in the service record instead of separate related lists.
const inServiceRecord:Kind[]=['hunts','duties','chronicle','promotions'];
function RecordView({kind,id,data}:{kind:Kind;id:string;data:Dataset}){const r=data[kind].find(r=>r.id===id);if(!r)return <div className="state">Record unavailable. <a href={href(kind)}>Back to {schemas[kind].title.toLowerCase()}</a></div>;const related: {kind:Kind;rows:RecordData[]}[]=kinds.filter(k=>kind!=='members'||!inServiceRecord.includes(k)).map(k=>({kind:k,rows:data[k].filter(other=>schemas[k].fields.some(f=>f.ref===kind&&other[f.key]===id))})).filter(g=>g.rows.length>0);return <><div className="record-actions"><a className="back" href={href(kind==='promotions'?'members':kind)}>{schemas[kind==='promotions'?'members':kind].title}</a><button type="button" onClick={()=>window.print()}>{kind==='members'?'Print profile':'Print record'}</button></div><article className="record-view"><p className="record-id">{r.id}{r.archived?' · archived':''}</p><h2>{r.name}</h2><dl>{schemas[kind].fields.filter(f=>f.key!=='name'&&(f.ref||(r[f.key]!=null&&r[f.key]!==''))).map(f=><div className={f.type==='textarea'?'wide':''} key={f.key}><dt>{f.label}</dt><dd>{f.ref?<Ref kind={f.ref} id={r[f.key]} data={data}/>:f.type==='url'?<External url={r[f.key]}>Open source</External>:String(r[f.key])}</dd></div>)}</dl></article>{kind==='members'&&<><Section title="Rank"><RankTrack member={r} data={data}/></Section><Section title="Service record"><p className="section-note">Ordered by real-world date. In-character dates are shown as written.</p><ServiceRecord member={r} data={data}/></Section></>}{related.map(g=><Section key={g.kind} title={`Related ${schemas[g.kind].title.toLowerCase()}`}><RecordList kind={g.kind} rows={g.rows} data={data}/></Section>)}</>;}
type Selected={from:RecordData;to:RecordData};
function Politics({data}:{data:Dataset}){
 const clans=active(data.clans);const [selected,setSelected]=useState<Selected|null>(null);
 const unequal=asymmetries(data),pairs=clans.flatMap((a,i)=>clans.slice(i+1).filter(b=>currentRelation(data,a.id,b.id)&&currentRelation(data,b.id,a.id))).length;
 const name=(id:unknown)=>clans.find(c=>c.id===id)?.name||String(id);
 return <><p className="summary">Each row shows that affiliation’s stance toward the one in each column. The two directions are assessed separately.</p>
 {clans.length?<div className="table-scroll" tabIndex={0} role="region" aria-label="Directional relations matrix"><table className="matrix"><thead><tr><th scope="col">From ↓ toward →</th>{clans.map(c=><th scope="col" key={c.id}>{c.name}<small>{c.kind}</small></th>)}</tr></thead><tbody>{clans.map(from=><tr key={from.id}><th scope="row"><a href={href('clans',from.id)}>{from.name}</a><small>{from.kind}</small></th>{clans.map(to=>{
  if(from.id===to.id)return <td key={to.id}><span className="muted" aria-label="Self relation">–</span></td>;
  const rel=currentRelation(data,from.id,to.id),back=currentRelation(data,to.id,from.id),stance=String(rel?.stance||'Unknown'),differs=!!(rel&&back&&back.stance!==rel.stance);
  return <td key={to.id}><button className={`stance stance-${slug(stance)}${differs?' differs':''}`} aria-pressed={selected?.from.id===from.id&&selected.to.id===to.id} onClick={()=>setSelected({from,to})} aria-label={`${from.name} toward ${to.name}: ${stance}${differs?`. ${to.name} toward ${from.name} is ${back!.stance}`:''}`}>{stance}{differs&&<span className="differs-mark" aria-hidden="true">≠</span>}</button></td>;
 })}</tr>)}</tbody></table></div>:<Empty>No affiliations recorded.</Empty>}
 {unequal.length>0&&<p className="section-note matrix-key"><span className="differs-mark" aria-hidden="true">≠</span> The reverse direction holds a different stance.</p>}
 {selected&&<Assessment selected={selected} data={data} onClose={()=>setSelected(null)}/>}
 {clans.length>1&&<Section title="Unequal relations"><p className="section-note">Pairs where each side holds a different stance toward the other. Pairs missing either direction are not compared.</p>{unequal.length?<ul className="record-list">{unequal.map(({forward,back})=><li key={forward.id}><div><span className="record-title">{name(forward.from)} and {name(forward.to)}</span><small>{name(forward.from)} toward {name(forward.to)}: {forward.stance}. {name(back.from)} toward {name(back.to)}: {back.stance}.</small></div></li>)}</ul>:<Empty>{pairs?'Every pair assessed in both directions holds the same stance both ways.':'No pair has both directions assessed yet.'}</Empty>}</Section>}
 </>;
}
function Assessment({selected:{from,to},data,onClose}:{selected:Selected;data:Dataset;onClose:()=>void}){
 const all=assessmentHistory(data,from.id,to.id),current=all.find(r=>!r.archived),earlier=all.filter(r=>r.archived);
 return <section className="section assessment" aria-label="Selected assessment"><div className="section-heading"><h2>{current?.name||`${from.name} toward ${to.name}`}</h2><button onClick={onClose}>Close assessment</button></div>
  <p><span className={`stance stance-${slug(current?.stance||'Unknown')}`}>{current?.stance||'Unknown'}</span>{current?.assessed&&<small className="assessed">Assessed {String(current.assessed)}</small>}</p>
  <p className="prose">{current?(current.notes||'No reasons recorded.'):'No current assessment has been recorded.'}</p>{current?.source&&<External url={current.source}>Assessment source</External>}
  {earlier.length>0&&<><h3 className="earlier-heading">Earlier assessments</h3><ol className="stance-history">{earlier.map(r=><li key={r.id}><span className={`stance stance-${slug(r.stance)}`}>{String(r.stance)}</span><div><a href={href('relations',r.id)}>{r.name}</a><small>{r.assessed?`Assessed ${String(r.assessed)}`:'Assessment date not recorded'}</small></div></li>)}</ol></>}
 </section>;
}
function Glossary({data}:{data:Dataset}){
 const [query,setQuery]=useState(''),[standing,setStanding]=useState('');
 const q=normalize(query),letter=(r:RecordData)=>normalize(r.name).replace(/^[^a-z]+/,'').charAt(0).toUpperCase()||'#';
 const rows=active(data.glossary).filter(r=>(!standing||r.status===standing)&&(!q||normalize(r.name).includes(q)||normalize(r.meaning).includes(q))).sort((a,b)=>normalize(a.name).replace(/^[^a-z]+/,'').localeCompare(normalize(b.name).replace(/^[^a-z]+/,'')));
 const standings=schemas.glossary.fields.find(f=>f.key==='status')!.options!;
 return <><p className="summary">Working meanings used in the clan’s roleplay. Provisional and disputed entries are not established translations.</p>
  <div className="filters"><label>Search terms and meanings<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Term or meaning"/></label><label>Standing<select value={standing} onChange={e=>setStanding(e.target.value)}><option value="">All</option>{standings.map(s=><option key={s}>{s}</option>)}</select></label></div>
  {!active(data.glossary).length?<Empty>No terms recorded.</Empty>:!rows.length?<Empty>No terms match.</Empty>:<dl className="glossary">{rows.map((r,i)=><div key={r.id} className="term">{(i===0||letter(r)!==letter(rows[i-1]))&&<span className="term-letter" aria-hidden="true">{letter(r)}</span>}<dt><a href={href('glossary',r.id)}>{r.name}</a><span className={`standing standing-${slug(r.status)}`}>{r.status}</span></dt><dd><span className="meaning">{r.meaning}</span>{r.category&&<small>{r.category}</small>}{r.usage&&<p>{r.usage}</p>}{r.doc&&<small>See <Ref kind="library" id={r.doc} data={data}/></small>}</dd></div>)}</dl>}
 </>;
}
