import { useEffect, useState, type ReactNode } from 'react';
import { Crosshair, Users, House, Target, BookOpen, Shield, Network, Files, ArrowUpRight, Menu } from 'lucide-react';
import { active, emptyData, kinds, openHunts, ordered, safeUrl, schemas, type Dataset, type Kind, type RecordData } from './model';
import { client, loadData, localPreview } from './service';
import { Admin } from './Admin';
const navigation=[['dashboard','Dashboard',Crosshair],['members','Hunters',Users],['houses','Households',House],['hunts','Undertakings',Target],['chronicle','History',BookOpen],['duties','Duties',Shield],['politics','Politics',Network],['library','Documents',Files]] as const;
const href=(kind:string,id?:string)=>`#/${kind}${id?'/'+encodeURIComponent(id):''}`;
export function External({url,children}:{url:unknown;children:ReactNode}){const safe=safeUrl(url);return safe?<a href={safe} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={14} aria-label="opens in a new tab"/></a>:<span>{children} <small>(link unavailable)</small></span>;}
export function App(){
 const [route,setRoute]=useState(location.hash.slice(2)||'dashboard'),[data,setData]=useState<Dataset>(emptyData),[status,setStatus]=useState('loading'),[error,setError]=useState(''),[mobile,setMobile]=useState(false),[refresh,setRefresh]=useState(0);
 const [section,id]=route.split('/');
 useEffect(()=>{const update=()=>{setRoute(location.hash.slice(2)||'dashboard');setMobile(false);window.scrollTo(0,0);};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
 useEffect(()=>{let current=true;setStatus('loading');loadData().then(d=>{if(current){setData(d);setStatus('ready');}}).catch(e=>{if(current){setError(e.message);setStatus('error');}});return()=>{current=false;};},[refresh]);
 useEffect(()=>{const reload=()=>setRefresh(n=>n+1);window.addEventListener('focus',reload);return()=>window.removeEventListener('focus',reload);},[]);
 const title=navigation.find(n=>n[0]===section)?.[1]||schemas[section as Kind]?.title||(section==='admin'?'Administration':'Page not found');
 const settings=active(data.settings)[0];
 return <><a className="skip" href="#main">Skip to content</a><header className="topbar"><a className="brand" href={href('dashboard')}><Crosshair size={31}/><span>TJAU’KE<small>CLAN ARCHIVE</small></span></a><div className="top-actions">{settings?.rulesUrl&&<External url={settings.rulesUrl}>Honour code</External>}<a href={href('admin')}>Administration</a><button className="menu" aria-label="Toggle navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}><Menu/></button></div></header><div className="layout"><aside className={mobile?'sidebar open':'sidebar'}><nav aria-label="Main navigation">{navigation.map(([key,label,Icon])=><a key={key} aria-current={section===key?'page':undefined} href={href(key)}><Icon size={18}/>{label}{status==='ready'&&key!=='dashboard'&&<span>{active(data[key==='politics'?'clans':key]).length}</span>}</a>)}</nav><div className="sidebar-foot"><span className="target-mark">┌ &nbsp; + &nbsp; ┐</span><p>Clan records<br/><small>Public archive</small></p></div></aside><main id="main" tabIndex={-1}><div className="page-heading"><div><p className="eyebrow">TJAU’KE / {section==='admin'?'ADMINISTRATION':'ARCHIVE'}</p><h1>{title}</h1></div><span className="access-label">{section==='admin'?'RESTRICTED ACCESS':'READ ONLY'}</span></div>{localPreview&&!client&&<div className="notice">Local preview · Workbook snapshot read 2 October 2026. Changes are not saved. Player handles are withheld.</div>}
 {section==='admin'?<Admin onChanged={()=>setRefresh(n=>n+1)}/>:status==='loading'?<div className="state" role="status">Loading clan records…</div>:status==='error'?<div className="state error" role="alert"><h2>Records unavailable</h2><p>{error}</p><button onClick={()=>setRefresh(n=>n+1)}>Try again</button></div>:id&&kinds.includes(section as Kind)?<RecordView kind={section as Kind} id={decodeURIComponent(id)} data={data}/>:section==='dashboard'?<Dashboard data={data}/>:section==='politics'?<Politics data={data}/>:kinds.includes(section as Kind)?<Collection key={section} kind={section as Kind} data={data}/>:<div className="state">This page does not exist. <a href={href('dashboard')}>Return to Dashboard</a></div>}
 <footer>Tjau’ke clan archive <span>Colonial Marines Universe · Community project</span></footer></main></div></>;
}
function Ref({kind,id,data}:{kind:Kind;id:unknown;data:Dataset}){if(!id)return <span className="muted">Not recorded</span>;const r=data[kind].find(r=>r.id===id);return r?<a href={href(kind,r.id)}>{r.name}{r.archived?' (archived)':''}</a>:<span className="muted">Missing reference · {String(id)}</span>;}
function Panel({title,to,children,className=''}:{title:string;to:string;children:ReactNode;className?:string}){return <section className={`panel ${className}`}><div className="panel-heading"><h2>{title}</h2><a href={href(to)}>View all <span aria-hidden="true">→</span></a></div>{children}</section>;}
function Empty({children='No records yet.'}:{children?:ReactNode}){return <p className="empty">{children}</p>;}
function RecordList({kind,rows,data}:{kind:Kind;rows:RecordData[];data:Dataset}){return rows.length?<ul className="record-list">{rows.map(r=><li key={r.id}><div><a className="record-title" href={href(kind,r.id)}>{r.name}</a><small>{kind==='hunts'?<Ref kind="members" id={r.hunter} data={data}/>:String(r.era||r.category||r.meaning||r.mandate||'')}</small></div>{(r.state||r.certainty||r.status)&&<span className="badge">{String(r.state||r.certainty||r.status)}</span>}</li>)}</ul>:<Empty/>;}
function Roster({rows,data}:{rows:RecordData[];data:Dataset}){return rows.length?<div className="table-scroll"><table className="roster"><thead><tr><th>Hunter</th><th>Rank</th><th>Household</th><th>Standing</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><th scope="row"><a href={href('members',r.id)}>{r.name}</a>{r.player&&<small>{r.player}</small>}</th><td>{r.rank||'Not recorded'}</td><td><Ref kind="houses" id={r.house} data={data}/></td><td><span className="badge">{r.status||'Not recorded'}</span></td></tr>)}</tbody></table></div>:<Empty>No hunters recorded.</Empty>;}
function Dashboard({data}:{data:Dataset}){const members=active(data.members),hunts=openHunts(data.hunts),duties=active(data.duties).filter(r=>['Active','Acting'].includes(String(r.status))&&!r.end);return <><div className="stats">{(['members','houses','hunts','chronicle','library'] as Kind[]).map(k=><a key={k} href={href(k)}><strong>{active(data[k]).length}</strong><span>{schemas[k].title}</span></a>)}</div><div className="dashboard-grid"><Panel title="Hunters" to="members" className="roster-panel"><Roster rows={members.slice(0,6)} data={data}/></Panel><Panel title="Open undertakings" to="hunts"><RecordList kind="hunts" rows={hunts} data={data}/></Panel><Panel title="Households & duties" to="houses"><RecordList kind="houses" rows={active(data.houses)} data={data}/><div className="subheading"><h3>Current duties</h3><a href={href('duties')}>All duties →</a></div>{duties.length?duties.map(r=><div className="duty-line" key={r.id}><a href={href('duties',r.id)}>{r.name}</a><Ref kind="members" id={r.member} data={data}/></div>):<Empty>No current appointments.</Empty>}</Panel><Panel title="Documents" to="library" className="documents-panel"><DocumentList rows={ordered(active(data.library)).slice(0,5)}/></Panel><Panel title="History" to="chronicle"><RecordList kind="chronicle" rows={ordered(active(data.chronicle)).slice(0,4)} data={data}/></Panel></div></>;}
function DocumentList({rows}:{rows:RecordData[]}){return rows.length?<ul className="record-list">{rows.map(r=><li key={r.id}><div><External url={r.url}>{r.name}</External><small>{r.category}</small>{r.summary&&<p>{r.summary}</p>}<a className="detail-link" href={href('library',r.id)}>Record details →</a></div></li>)}</ul>:<Empty>No documents in this shelf.</Empty>;}
function Collection({kind,data}:{kind:Kind;data:Dataset}){const [query,setQuery]=useState(''),[archived,setArchived]=useState(false),[filter,setFilter]=useState('');const filterKey=kind==='library'?'category':kind==='hunts'?'state':kind==='members'?'rank':'';const rows=ordered(data[kind].filter(r=>(archived||!r.archived)&&String(r.name).toLowerCase().includes(query.toLowerCase())&&(!filter||r[filterKey]===filter)));return <><div className="filters"><label>Search {schemas[kind].title.toLowerCase()}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name…"/></label>{filterKey&&<label>{kind==='library'?'Shelf':kind==='hunts'?'Undertaking state':'Rank'}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All</option>{[...new Set(data[kind].map(r=>String(r[filterKey]||'')).filter(Boolean))].sort().map(v=><option key={v}>{v}</option>)}</select></label>}<label className="checkbox"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Include archived</label></div><section className="panel">{kind==='members'?<Roster rows={rows} data={data}/>:kind==='library'?<DocumentList rows={rows}/>:kind==='chronicle'?rows.length?rows.map(r=><details className="history-entry" key={r.id}><summary><span><strong>{r.name}</strong><small>{r.era||'Era not recorded'}</small></span><span className="badge">{r.certainty||'Not classified'}</span></summary>{r.summary&&<p>{r.summary}</p>}<p className="prose">{r.body}</p><a href={href(kind,r.id)}>References & record details →</a></details>):<Empty>No matching history entries.</Empty>:<RecordList kind={kind} rows={rows} data={data}/>}</section></>;}
function RecordView({kind,id,data}:{kind:Kind;id:string;data:Dataset}){const r=data[kind].find(r=>r.id===id);if(!r)return <div className="state">Record unavailable. <a href={href(kind)}>Back to {schemas[kind].title}</a></div>;const related: {kind:Kind;rows:RecordData[]}[]=kinds.map(k=>({kind:k,rows:data[k].filter(other=>schemas[k].fields.some(f=>f.ref===kind&&other[f.key]===id))})).filter(g=>g.rows.length>0);return <><a className="back" href={href(kind)}>← {schemas[kind].title}</a><article className="panel record-view"><p className="eyebrow">{r.id}{r.archived?' / ARCHIVED':''}</p><h2>{r.name}</h2><dl>{schemas[kind].fields.filter(f=>f.key!=='name'&&r[f.key]!==undefined&&r[f.key]!=='').map(f=><div className={f.type==='textarea'?'wide':''} key={f.key}><dt>{f.label}</dt><dd>{f.ref?<Ref kind={f.ref} id={r[f.key]} data={data}/>:f.type==='url'?<External url={r[f.key]}>Open source</External>:String(r[f.key])}</dd></div>)}</dl></article>{related.map(g=><Panel key={g.kind} title={`Related ${schemas[g.kind].title.toLowerCase()}`} to={g.kind}><RecordList kind={g.kind} rows={g.rows} data={data}/></Panel>)}</>;}
function Politics({data}:{data:Dataset}){const clans=active(data.clans);const [selected,setSelected]=useState<RecordData|null>(null);return <><p className="intro">Read from row to column. Each direction is assessed independently.</p>{clans.length?<section className="panel"><div className="table-scroll" tabIndex={0} role="region" aria-label="Directional relations matrix"><table className="matrix"><thead><tr><th scope="col">From ↓ / Toward →</th>{clans.map(c=><th scope="col" key={c.id}>{c.name}<small>{c.kind}</small></th>)}</tr></thead><tbody>{clans.map(from=><tr key={from.id}><th scope="row"><a href={href('clans',from.id)}>{from.name}</a><small>{from.kind}</small></th>{clans.map(to=>{const rel=active(data.relations).find(r=>r.from===from.id&&r.to===to.id);return <td key={to.id}>{from.id===to.id?<span aria-label="Self relation">—</span>:<button className={`stance stance-${String(rel?.stance||'Unknown').toLowerCase()}`} onClick={()=>setSelected(rel||{id:'',archived:false,published:true,name:`${from.name} → ${to.name}`,stance:'Unknown',notes:'No assessment has been recorded.'})} aria-label={`${from.name} toward ${to.name}: ${rel?.stance||'Unknown'}`}>{rel?.stance||'Unknown'}</button>}</td>;})}</tr>)}</tbody></table></div></section>:<Empty>No affiliations recorded.</Empty>}{selected&&<section className="panel assessment" aria-label="Selected assessment"><div className="panel-heading"><h2>{selected.name}</h2><button onClick={()=>setSelected(null)}>Close</button></div><p><span className={`stance stance-${String(selected.stance).toLowerCase()}`}>{selected.stance}</span></p><p className="prose">{selected.notes||'No reasons recorded.'}</p>{selected.source&&<External url={selected.source}>Assessment source</External>}</section>}</>;}
