import { useEffect, useState, type ReactNode } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { active, emptyData, kinds, openHunts, ordered, safeUrl, schemas, type Dataset, type Kind, type RecordData } from './model';
import { client, loadData, localPreview } from './service';
import { Admin } from './Admin';
const navigation=[['dashboard','Overview'],['members','Hunters'],['houses','Households'],['hunts','Undertakings'],['chronicle','History'],['duties','Duties'],['politics','Politics'],['library','Documents']] as const;
const href=(kind:string,id?:string)=>`#/${kind}${id?'/'+encodeURIComponent(id):''}`;
const plural=(n:number,one:string,many:string)=>`${n} ${n===1?one:many}`;
export function External({url,children}:{url:unknown;children:ReactNode}){const safe=safeUrl(url);return safe?<a className="external" href={safe} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={14} aria-label="opens in a new tab"/></a>:<span>{children} <small>(link unavailable)</small></span>;}
function Mark(){return <svg className="mark" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="4.6" r="2.4"/><circle cx="5.2" cy="17.4" r="2.4"/><circle cx="18.9" cy="16.8" r="2.4"/></svg>;}
export function App(){
 const [route,setRoute]=useState(location.hash.slice(2)||'dashboard'),[data,setData]=useState<Dataset>(emptyData),[status,setStatus]=useState('loading'),[error,setError]=useState(''),[mobile,setMobile]=useState(false),[refresh,setRefresh]=useState(0);
 const [section,id]=route.split('/');
 useEffect(()=>{const update=()=>{setRoute(location.hash.slice(2)||'dashboard');setMobile(false);window.scrollTo(0,0);};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
 useEffect(()=>{let current=true;setStatus('loading');loadData().then(d=>{if(current){setData(d);setStatus('ready');}}).catch(e=>{if(current){setError(e.message);setStatus('error');}});return()=>{current=false;};},[refresh]);
 useEffect(()=>{const reload=()=>setRefresh(n=>n+1);window.addEventListener('focus',reload);return()=>window.removeEventListener('focus',reload);},[]);
 const title=navigation.find(n=>n[0]===section)?.[1]||schemas[section as Kind]?.title||(section==='admin'?'Administration':'Page not found');
 const settings=active(data.settings)[0];
 return <><a className="skip" href="#main">Skip to content</a><header className="topbar"><a className="brand" href={href('dashboard')}><Mark/><span>Tjau’ke<small>Clan archive</small></span></a><div className="top-actions">{settings?.rulesUrl&&<External url={settings.rulesUrl}>Honour code</External>}<a className="admin-link" href={href('admin')}>Administration</a><button className="menu" aria-expanded={mobile} aria-controls="sections" onClick={()=>setMobile(!mobile)}>{mobile?'Close':'Menu'}</button></div></header><div className="layout"><aside id="sections" className={mobile?'sidebar open':'sidebar'}><nav aria-label="Archive sections">{navigation.map(([key,label])=><a key={key} aria-current={section===key?'page':undefined} href={href(key)}>{label}{status==='ready'&&key!=='dashboard'&&<span>{active(data[key==='politics'?'clans':key]).length}</span>}</a>)}</nav></aside><div className="content"><main id="main" tabIndex={-1}><h1>{title}</h1>{localPreview&&!client&&<div className="notice">Local preview of the workbook snapshot read on 2 October 2026. Changes are not saved and player handles are withheld.</div>}
 {section==='admin'?<Admin onChanged={()=>setRefresh(n=>n+1)}/>:status==='loading'?<div className="state" role="status">Loading clan records…</div>:status==='error'?<div className="state error" role="alert"><h2>Records unavailable</h2><p>{error}</p><button onClick={()=>setRefresh(n=>n+1)}>Try again</button></div>:id&&kinds.includes(section as Kind)?<RecordView kind={section as Kind} id={decodeURIComponent(id)} data={data}/>:section==='dashboard'?<Dashboard data={data}/>:section==='politics'?<Politics data={data}/>:kinds.includes(section as Kind)?<Collection key={section} kind={section as Kind} data={data}/>:<div className="state">This page does not exist. <a href={href('dashboard')}>Back to the overview</a></div>}
 </main><footer>Tjau’ke clan archive, a Colonial Marines Universe community project</footer></div></div></>;
}
function Ref({kind,id,data}:{kind:Kind;id:unknown;data:Dataset}){if(!id)return <span className="muted">Not recorded</span>;const r=data[kind].find(r=>r.id===id);return r?<a href={href(kind,r.id)}>{r.name}{r.archived?' (archived)':''}</a>:<span className="muted">Missing reference: {String(id)}</span>;}
function Section({title,to,link,children,className=''}:{title:string;to?:string;link?:string;children:ReactNode;className?:string}){return <section className={`section ${className}`}><div className="section-heading"><h2>{title}</h2>{to&&<a href={href(to)}>{link}</a>}</div>{children}</section>;}
function Empty({children='No records yet.'}:{children?:ReactNode}){return <p className="empty">{children}</p>;}
function RecordList({kind,rows,data}:{kind:Kind;rows:RecordData[];data:Dataset}){return rows.length?<ul className="record-list">{rows.map(r=><li key={r.id}><div><a className="record-title" href={href(kind,r.id)}>{r.name}</a><small>{kind==='hunts'?<Ref kind="members" id={r.hunter} data={data}/>:String(r.era||r.category||r.meaning||r.mandate||'')}</small></div>{(r.state||r.certainty||r.status)&&<span className="tag">{String(r.state||r.certainty||r.status)}</span>}</li>)}</ul>:<Empty/>;}
function Roster({rows,data}:{rows:RecordData[];data:Dataset}){return rows.length?<div className="table-scroll"><table className="roster"><thead><tr><th>Hunter</th><th>Rank</th><th>Household</th><th>Standing</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><th scope="row"><a href={href('members',r.id)}>{r.name}</a>{r.player&&<small>{r.player}</small>}</th><td>{r.rank||<span className="muted">Not recorded</span>}</td><td><Ref kind="houses" id={r.house} data={data}/></td><td>{r.status||<span className="muted">Not recorded</span>}</td></tr>)}</tbody></table></div>:<Empty>No hunters recorded.</Empty>;}
function Dashboard({data}:{data:Dataset}){
 const members=active(data.members),houses=active(data.houses),hunts=openHunts(data.hunts),history=active(data.chronicle),docs=active(data.library),duties=active(data.duties).filter(r=>['Active','Acting'].includes(String(r.status))&&!r.end);
 return <><p className="summary">{plural(members.length,'hunter','hunters')} across {plural(houses.length,'household','households')}. {hunts.length?plural(hunts.length,'undertaking is','undertakings are')+' open.':'No undertakings are open.'}</p><div className="overview"><div className="overview-main"><Section title="Hunters" to="members" link={members.length>6?`Full roster (${members.length})`:'Full roster'}><Roster rows={members.slice(0,6)} data={data}/></Section><Section title="History" to="chronicle" link="All history"><RecordList kind="chronicle" rows={ordered(history).slice(0,4)} data={data}/></Section></div><div className="overview-side"><Section title="Open undertakings" to="hunts" link="All undertakings">{hunts.length?<RecordList kind="hunts" rows={hunts} data={data}/>:<Empty>No open undertakings.</Empty>}</Section><Section title="Households" to="houses" link="All households"><RecordList kind="houses" rows={houses} data={data}/></Section><Section title="Current duties" to="duties" link="All duties">{duties.length?<ul className="record-list compact">{duties.map(r=><li key={r.id}><a href={href('duties',r.id)}>{r.name}</a><Ref kind="members" id={r.member} data={data}/></li>)}</ul>:<Empty>No current appointments.</Empty>}</Section><Section title="Documents" to="library" link="All documents"><DocumentList rows={ordered(docs).slice(0,5)}/></Section></div></div></>;
}
function DocumentList({rows}:{rows:RecordData[]}){return rows.length?<ul className="record-list">{rows.map(r=><li key={r.id}><div><External url={r.url}>{r.name}</External><small>{r.category}{r.category?' · ':''}<a href={href('library',r.id)}>Details</a></small>{r.summary&&<p>{r.summary}</p>}</div></li>)}</ul>:<Empty>No documents on this shelf.</Empty>;}
function Collection({kind,data}:{kind:Kind;data:Dataset}){const [query,setQuery]=useState(''),[archived,setArchived]=useState(false),[filter,setFilter]=useState('');const filterKey=kind==='library'?'category':kind==='hunts'?'state':kind==='members'?'rank':'';const rows=ordered(data[kind].filter(r=>(archived||!r.archived)&&String(r.name).toLowerCase().includes(query.toLowerCase())&&(!filter||r[filterKey]===filter)));return <><div className="filters"><label>Search {schemas[kind].title.toLowerCase()}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name"/></label>{filterKey&&<label>{kind==='library'?'Shelf':kind==='hunts'?'State':'Rank'}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All</option>{[...new Set(data[kind].map(r=>String(r[filterKey]||'')).filter(Boolean))].sort().map(v=><option key={v}>{v}</option>)}</select></label>}<label className="checkbox"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Include archived</label></div><section className="section">{kind==='members'?<Roster rows={rows} data={data}/>:kind==='library'?<DocumentList rows={rows}/>:kind==='chronicle'?rows.length?rows.map(r=><details className="history-entry" key={r.id}><summary><span><strong>{r.name}</strong><small>{r.era||'Era not recorded'}</small></span><span className="tag">{r.certainty||'Not classified'}</span></summary>{r.summary&&<p>{r.summary}</p>}<p className="prose">{r.body}</p><a href={href(kind,r.id)}>Sources and references</a></details>):<Empty>No history entries match.</Empty>:<RecordList kind={kind} rows={rows} data={data}/>}</section></>;}
function RecordView({kind,id,data}:{kind:Kind;id:string;data:Dataset}){const r=data[kind].find(r=>r.id===id);if(!r)return <div className="state">Record unavailable. <a href={href(kind)}>Back to {schemas[kind].title.toLowerCase()}</a></div>;const related: {kind:Kind;rows:RecordData[]}[]=kinds.map(k=>({kind:k,rows:data[k].filter(other=>schemas[k].fields.some(f=>f.ref===kind&&other[f.key]===id))})).filter(g=>g.rows.length>0);return <><a className="back" href={href(kind)}>{schemas[kind].title}</a><article className="record-view"><p className="record-id">{r.id}{r.archived?' · archived':''}</p><h2>{r.name}</h2><dl>{schemas[kind].fields.filter(f=>f.key!=='name'&&(f.ref||(r[f.key]!=null&&r[f.key]!==''))).map(f=><div className={f.type==='textarea'?'wide':''} key={f.key}><dt>{f.label}</dt><dd>{f.ref?<Ref kind={f.ref} id={r[f.key]} data={data}/>:f.type==='url'?<External url={r[f.key]}>Open source</External>:String(r[f.key])}</dd></div>)}</dl></article>{related.map(g=><Section key={g.kind} title={`Related ${schemas[g.kind].title.toLowerCase()}`}><RecordList kind={g.kind} rows={g.rows} data={data}/></Section>)}</>;}
function Politics({data}:{data:Dataset}){const clans=active(data.clans);const [selected,setSelected]=useState<RecordData|null>(null);return <><p className="summary">Each row shows that affiliation’s stance toward the one in each column. The two directions are assessed separately.</p>{clans.length?<div className="table-scroll" tabIndex={0} role="region" aria-label="Directional relations matrix"><table className="matrix"><thead><tr><th scope="col">From ↓ toward →</th>{clans.map(c=><th scope="col" key={c.id}>{c.name}<small>{c.kind}</small></th>)}</tr></thead><tbody>{clans.map(from=><tr key={from.id}><th scope="row"><a href={href('clans',from.id)}>{from.name}</a><small>{from.kind}</small></th>{clans.map(to=>{const rel=active(data.relations).find(r=>r.from===from.id&&r.to===to.id);return <td key={to.id}>{from.id===to.id?<span className="muted" aria-label="Self relation">–</span>:<button className={`stance stance-${String(rel?.stance||'Unknown').toLowerCase()}`} onClick={()=>setSelected(rel||{id:'',archived:false,published:true,name:`${from.name} → ${to.name}`,stance:'Unknown',notes:'No assessment has been recorded.'})} aria-label={`${from.name} toward ${to.name}: ${rel?.stance||'Unknown'}`}>{rel?.stance||'Unknown'}</button>}</td>;})}</tr>)}</tbody></table></div>:<Empty>No affiliations recorded.</Empty>}{selected&&<section className="section assessment" aria-label="Selected assessment"><div className="section-heading"><h2>{selected.name}</h2><button onClick={()=>setSelected(null)}>Close</button></div><p><span className={`stance stance-${String(selected.stance).toLowerCase()}`}>{selected.stance}</span></p><p className="prose">{selected.notes||'No reasons recorded.'}</p>{selected.source&&<External url={selected.source}>Assessment source</External>}</section>}</>;}
