-- Living Chronicle: separate Honor Code worthiness from the Measure of Prey, make "the Quarry Must Know" a stalking rule
-- rather than a duel, and keep synthetics unhuntable while still respected.
-- Run once after 202610090001_document_text.sql. Replaces whole paragraphs, found by their opening words.
-- Stops and changes nothing if a paragraph cannot be found exactly once; safe to rerun once applied.
begin;

create or replace function pg_temp.swap(body text, prefix text, replacement text) returns text language plpgsql as $$
declare pattern text := '^[ \t]*' || prefix || '.*$'; hits int;
begin
 select count(*) into hits from regexp_matches(body, pattern, 'gn');
 if hits = 1 then return regexp_replace(body, pattern, replacement, 'n'); end if;
 if hits = 0 and position(replacement in body) > 0 then return body; end if;
 raise exception 'Living Chronicle: paragraph starting "%" found % times; nothing was changed', prefix, hits;
end; $$;

do $migration$
declare doc_id text; doc_text text; found int;
begin
 select count(*), min(id) into found, doc_id from public.library
  where id = 'DOC-2F08DD45-B36';
 if found <> 1 then raise exception 'Living Chronicle: expected one matching document, found %', found; end if;
 select l.body into doc_text from public.library l where id = doc_id;

 -- No text yet: start from the Google Doc as it stood on 4 October 2026.
 if length(trim(coalesce(doc_text, ''))) = 0 then doc_text := $doc$> “CHOOSE YOUR BURDEN. HONOR YOUR OATH.”
## Overview
The Tjau'ke are an ancient Yautja clan whose recorded history stretches back 18,733 reckoning-years to the First Mark. They are best known for a hunting tradition that is stricter than the usual honor code. To them, simply carrying a weapon or being dangerous is not enough to make someone worthy prey.
A Tjau'ke hunter watches first. Worth has to be proven through skill, courage, intelligence, leadership, survival instinct, or some other ability that makes the target a genuine threat. A terrified soldier holding a rifle might interest them less than an unarmed officer who has somehow kept an entire squad alive through impossible circumstances.
Once the hunter decides that a target is worthy, they deliberately give up part of their own advantage. The weaker the prey, the greater that burden is expected to be. A hunter might leave the plasma caster behind, swear off the cloak once the Hunt begins, limit themselves to a single weapon, or accept some other restriction that gives the quarry a real chance.
That choice is made before the Hunt and cannot simply be changed halfway through. If the prey turns out to be far more dangerous than expected, the hunter can continue or withdraw. What they cannot do is reach for a weapon they already swore not to use simply because they misjudged their opponent.
The prey must also understand that it is being hunted. A Tjau'ke may observe and stalk a target without being seen, but killing someone who never knew there was a Hunt is not considered a proper trophy. At some point, the hunter has to make the threat clear—a challenge, a deliberate uncloaking, a near miss, or some other warning the quarry can understand.
These traditions apply specifically to Hunts, not to every form of violence. In war, defense, rescue, or containment, the Tjau'ke use whatever is necessary to keep their people alive. A boarding action is not a Hunt, and a Xenomorph loose aboard a clan vessel is something to kill quickly, not a trophy to earn.
That does not stop the clan from boasting, competing, and arguing over who accepted the harder burden. Some hunters choose their restrictions carefully. Others make promises that everyone around them considers completely foolish. What matters is that once the choice is made, they live with it.
A difficult kill proves skill. A difficult kill made under a burden you willingly chose proves something more.
## The First Mark
The clan traces its formal beginning to an event known as the Seven Departures.
Before that, several related hunting lines shared territory, routes and enemies, but not the same rules. Some valued close combat above all else. Others cared more about trophies. Some were willing to use almost any advantage, so long as the quarry still had a chance to fight back.
During the Seven Departures, seven vessels entered the same hunting region in pursuit of prey considered dangerous, but technologically inferior. At first, the Hunts were easy. Then the prey adapted. They began laying traps, coordinating ambushes and even using captured Yautja equipment against the hunters.
The groups did not agree on how to respond. Some withdrew. Some kept to the limits they had set for themselves. Others brought out heavier weapons and started killing anything that stood in their way while still insisting that what they were doing was a Hunt.
The argument that followed them home became more important than the losses themselves.
The eventual settlement was simple: a hunter could place almost any restriction on themselves, but once the Hunt began, they were bound by it.
Formal Hunts soon began to carry a visible sign that such restrictions had been chosen. Early marks took the form of cuts, knots or seals placed over weapons that were not to be used. The custom became known as the First Mark, and in time the name also came to refer to the agreement itself.
The settlement also rejected the idea that worth could be judged by species, rank or appearance alone. It had to be proven. A hunter was expected to know why a particular individual had been chosen instead of simply taking the easiest armed target available.
The prey also had to understand, at some point, that it was being hunted. Stalking and surprise were still acceptable, but a true Hunt was expected to become a contest before the kill, even if that contest was badly uneven.
Withdrawal was permitted. Breaking the oath was not. A hunter who had misjudged the quarry could leave and carry the shame home with them. What they could not do was change the rules halfway through and pretend the original promise had never been made.
Modern Tjau'ke still argue over the details, but the old principles remain.
## The Households
Six households remain active in the present era. They all follow the same basic laws of the Hunt, but they do not always agree on what makes prey worthy, or how far a hunter should go in limiting themselves.
Vek'ta is the oldest household and usually the most traditional. Its hunters favor direct challenges, close pursuit, and simple oaths with little room for interpretation. Vek'ta sponsors are respected for their discipline, though younger hunters often find them unforgiving. Once an oath is made, excuses carry little weight.
Khe'rat is known for its armorers, weapon-smiths, and engineers. Its approach to the Bound Hunt is practical rather than ceremonial. Systems that have been sworn off are locked, sealed, or removed before departure. A hunter who gives up the use of plasma, for example, may leave the caster behind entirely or seal its controls so that breaking the oath requires a deliberate choice.
Sa'rahn maintains many of the clan's routes and produces a large share of its scouts. Its hunters are closely associated with the Measure of Prey and may observe a target for hours before deciding whether it is worth challenging. They care less about how many weapons a quarry carries than how it leads, adapts, survives, and responds under pressure.
Taal'vek is closely tied to training and first Hunts. Its sponsors teach candidates to choose burdens that make the Hunt dangerous without turning it into pointless suicide. They have little respect for easy prey, but even less for young hunters who make reckless oaths simply to impress others.
Orh'kesh oversees medicine, xenobiology, and containment. Its hunters are often the first to argue that circumstances can change during a Hunt. A badly wounded or helpless quarry may no longer be worthy.
Dra'khal is the youngest household and the most military in character. It draws a hard line between hunting and war. During defense, boarding actions, rescue operations, or open conflict, its hunters use the full arsenal without hesitation. The principle of Equal Burden applies only when violence is chosen for the sake of the Hunt itself.
## Hunting, Blooding, and Judgement
For the Tjau'ke, a formal Hunt follows four basic principles: measure the prey, make it aware, accept a burden, and remain bound by that burden until the Hunt is over.
The Measure of Prey comes first. A target must have shown something that makes hunting them worthwhile. Combat skill is the obvious measure, but it is far from the only one. Leadership, intelligence, repeated survival, or simply being able to outthink stronger opponents can make someone worthy prey. Carrying a weapon by itself means very little.
Then comes the rule that the Worthy Must Know. A hunter may stalk and observe from cloak, but they cannot take the final kill while the quarry remains completely unaware of them. The warning does not have to be formal. A roar, a deliberate uncloaking, a weapon striking nearby, or a clear challenge can all serve the purpose.
Equal Burden determines what advantage the hunter gives up. It is not meant to make the fight literally fair. The point is to remove enough of the hunter's advantages that victory still carries some meaning. Against an ordinary armed human, that might mean giving up both plasma weapons and the cloak during combat. Against a heavily armed squad, far fewer restrictions may be necessary.
The burden itself is personal. One hunter might swear to use only a spear. Another may keep the cloak but abandon every ranged weapon. Choosing a cautious burden is not dishonorable, but crushing obviously weaker prey while risking almost nothing earns little respect.
Once those limits are spoken, the Bound Hunt begins. The hunter names the quarry, or the group being hunted, and states what they will not use. Some make the oath before a sponsor, others before companions, and some speak it where the prey can hear. The exact wording matters less than making the restriction clear enough that it cannot later be denied or reinterpreted.
A burden can become stricter, but never easier. A hunter who has sworn off plasma may later throw away the spear as well. They cannot decide halfway through the Hunt that plasma is acceptable after all. If the quarry proves more dangerous than expected, the hunter either continues under the original burden or abandons the Hunt.
Outside interference can end a Hunt without dishonor. If a third party enters the fight, the quarry is crippled by something unrelated, or the situation turns into open battle, the hunter is free to defend themselves normally. What they cannot do is use the chaos as an excuse to finish the original quarry with something their oath forbade.
These rules matter especially during a first Hunt. A candidate must choose worthy prey, accept an appropriate burden, make the challenge known, and finish the Hunt without breaking their word. The sponsor is there to judge the candidate's decisions, not to control the fight for them.
Blooding follows if the sponsor accepts that the candidate kept the oath and took worthy prey. If the candidate knowingly reaches for a forbidden advantage, the kill does not count.
Different households mark Blooding in different ways. Some engrave armor or masks, while others add cords, plates, or fittings. Khe'rat often keeps the seal used during the first Hunt. Sa'rahn, by contrast, may mark the place where the candidate first revealed themselves to the quarry.
Breaking a Hunt oath is one of the quickest ways to lose standing among the Tjau'ke. Retreat may earn mockery, and failure can be lived down. Deliberately breaking a restriction after giving your word is much harder to forgive.
## Clan Life
Most of Tjau'ke life has little to do with formal Hunts, but the idea of choosing your own burdens shows up everywhere.
Younglings are often trained with small restrictions: climb without using the left hand, track without a mask, spar without their favored weapon. The goal is not suffering for its own sake. It is to learn what you rely on—and what happens when that advantage is suddenly gone.
The clan is competitive, but rarely solemn about it. Hunters argue over whether someone's burden was too easy, mock friends who made an oath far harder than it needed to be, and remember bad decisions for years. Surviving an absurd oath can make someone famous. Making absurd oaths constantly mostly makes people tired of you.
Trophies matter for much the same reason. An ordinary skull taken with every advantage available may earn little attention. The same prey brought down without a cloak, ranged weapon, or some other familiar tool might still be talked about decades later.
Adoption and mixed households are common, so the Tjau'ke have never been one neat bloodline with one fixed idea of honor. Hunters bring customs and beliefs from elsewhere, and disagreements over what makes a good Hunt are normal. What matters more is that once an oath is made, it is kept.
Their equipment reflects this as well. Weapons tend to be modular, restraints and seals are common, and older armor may carry the marks of many previous Hunts. A missing weapon mount does not necessarily mean something broke. Sometimes the hunter removed it on purpose before leaving.
## Outsiders and Present Day
The Tjau'ke do not judge entire species as worthy or unworthy. They judge the individual. A weaker opponent can still prove worthy through planning, leadership, nerve, or simply by surviving again and again. A synthetic may earn the same regard if it shows genuine independence and judgment. An armed fool, meanwhile, may never interest them at all.
Relations with other clans are mixed. The Kha'drek remain openly hostile and often ridicule the Tjau'ke practice of warning prey before the kill. The Sa'keth are neutral, and their hunters have occasionally joined Tjau'ke Hunts under agreed restrictions. The descendants of Sha'korr remain estranged after an old dispute over whether a hunter is free to escalate once the prey proves more dangerous than expected.
Xenomorphs complicate the matter further. Few Tjau'ke would question whether they are worthy prey, but deciding what burden is appropriate is difficult when the danger can change in seconds. A Drone and a mature Praetorian clearly do not demand the same restraint, and the Hunt stops being a Hunt the moment a hive threatens a ship or settlement.
For that reason, Orh'kesh argues that once containment fails, the Hunt is over. From that point on, every available weapon is legitimate. Some Taal'vek traditionalists think Orh'kesh draws that line too quickly, particularly when a young hunter has chosen a Xenomorph for their first Blooding.
Human warfare causes similar arguments. One Marine on their own may be unremarkable. Put that same Marine in a disciplined squad with heavy weapons and capable leadership, however, and the situation changes completely. Sa'rahn argues that the hunter should judge the threat as it actually exists, rather than pretend the quarry stands alone.
Keth'tar, the current senior of Vek'ta, is among the strictest defenders of the Bound Hunt. When hunters complain that their prey turned out stronger than expected, his answer is usually simple: that was the point of measuring the prey beforehand.
The Tjau'ke do not try to make every Hunt fair. They try to make it meaningful. The prey must be worth choosing. It must know that it has become prey. And the hunter must willingly give up some part of their own advantage.
> “CHOOSE YOUR BURDEN. HONOR YOUR OATH.”$doc$; end if;

 -- 1. Honor Code worthiness decides who may be hunted; the Measure decides who is worth choosing.
 doc_text := pg_temp.swap(doc_text, $p$The Tjau['’]ke are an ancient Yautja clan$p$, $t$The Tjau'ke are an ancient Yautja clan whose recorded history stretches back 18,733 reckoning-years to the First Mark. They are best known for a hunting tradition that asks more of the hunter than the Honor Code does. The code decides who may be hunted at all. The Tjau'ke add a second question on top of it: of all the prey the code allows, which is worth choosing? Simply carrying a weapon or being dangerous is rarely enough.$t$);
 doc_text := pg_temp.swap(doc_text, $p$A Tjau['’]ke hunter watches first$p$, $t$A Tjau'ke hunter watches first. Their interest has to be earned through skill, courage, intelligence, leadership, survival instinct, or some other ability that makes the target a genuine threat. A terrified soldier holding a rifle may be lawful prey and still hold no interest at all. The soldier who kept six wounded comrades alive while the line collapsed is the one they want.$t$);
 doc_text := pg_temp.swap(doc_text, $p$Once the hunter decides that a target is worthy$p$, $t$Once the hunter has chosen a quarry, they deliberately give up part of their own advantage. The weaker the prey, the greater that burden is expected to be. A hunter might leave the plasma caster behind, swear off the cloak once the Hunt begins, limit themselves to a single weapon, or accept some other restriction that gives the quarry a real chance.$t$);
 doc_text := pg_temp.swap(doc_text, $p$The settlement also rejected the idea$p$, $t$The settlement did not change who could be hunted. It added a second question: of the prey a hunter was permitted to take, which was worth choosing? That could not be judged by species, rank or appearance alone. It had to be shown. A hunter was expected to know why a particular individual had been chosen instead of simply taking the easiest armed target available.$t$);
 doc_text := pg_temp.swap(doc_text, $p$Six households remain active$p$, $t$Six households remain active in the present era. They all follow the same basic laws of the Hunt, but they do not always agree on what makes prey worth choosing, or how far a hunter should go in limiting themselves.$t$);
 doc_text := pg_temp.swap(doc_text, $p$Orh['’]kesh oversees medicine$p$, $t$Orh'kesh oversees medicine, xenobiology, and containment. Its hunters are often the first to argue that circumstances can change during a Hunt. A badly wounded or helpless quarry may no longer be worth the Hunt.$t$);
 doc_text := pg_temp.swap(doc_text, $p$The Measure of Prey comes first$p$, $t$The Measure of Prey comes first, and it sits on top of the Honor Code rather than beside it. The code decides who may be hunted; the Measure decides who is worth hunting. Two Marines can be equally lawful prey and still not equally interesting. One is merely available. The other kept six wounded soldiers alive while the line collapsed, and that is the one a Tjau'ke wants. Combat skill is the obvious measure, but leadership, intelligence, repeated survival or outthinking stronger opponents count just as much. Carrying a weapon by itself means very little, and nothing in the Measure makes huntable anyone the code protects.$t$);
 doc_text := pg_temp.swap(doc_text, $p$These rules matter especially during a first Hunt$p$, $t$These rules matter especially during a first Hunt. A candidate must choose quarry that meets the Measure, accept an appropriate burden, make their presence known, and finish the Hunt without breaking their word. The sponsor is there to judge the candidate's decisions, not to control the fight for them.$t$);
 doc_text := pg_temp.swap(doc_text, $p$Blooding follows if the sponsor accepts$p$, $t$Blooding follows if the sponsor accepts that the candidate kept the oath and took quarry that met the Measure. If the candidate knowingly reaches for a forbidden advantage, the kill does not count.$t$);
 doc_text := pg_temp.swap(doc_text, $p$Xenomorphs complicate the matter further$p$, $t$Xenomorphs complicate the matter further. Few Tjau'ke would question whether they are worth hunting, but deciding what burden is appropriate is difficult when the danger can change in seconds. A Drone and a mature Praetorian clearly do not demand the same restraint, and the Hunt stops being a Hunt the moment a hive threatens a ship or settlement.$t$);

 -- 2. The quarry must come to know it is hunted; the hunter still stalks and strikes from concealment.
 doc_text := pg_temp.swap(doc_text, $p$The prey must also understand that it is being hunted$p$, $t$The quarry must also come to know, before the trophy is taken, that something is deliberately hunting it. This is not a duel, and the prey is never asked to accept a challenge. The hunter stalks and strikes from concealment like any other; the awareness can be as small as a glimpse, a sound, or a shot that misses on purpose. What the clan will not count as a proper trophy is a kill on prey that never knew it was being hunted.$t$);
 doc_text := pg_temp.swap(doc_text, $p$The prey also had to understand, at some point$p$, $t$The prey also had to understand, at some point, that it was being hunted. Stalking, concealment and surprise remained the hunter's tools; the settlement asked only that the quarry come to know, before the end, that it had become prey.$t$);
 doc_text := pg_temp.swap(doc_text, $p$Then comes the rule that the Worthy Must Know$p$, $t$Then comes the rule that the Quarry Must Know. The Tjau'ke are hunters, not duelists. A hunter stalks from concealment, watches, and picks the moment to strike, and nothing in the rule asks them to step into the open and announce themselves. What it asks is that, before the trophy is taken, the quarry has become aware that an intelligent, hostile presence is deliberately pursuing it. A roar, a shimmer where nothing should be, three red dots crossing a wall, or a blade striking a hand's width away is enough. The Marine turns at a click and sees nothing. Five minutes later someone is missing. That counts.$t$);
 doc_text := pg_temp.swap(doc_text, $p$The Tjau['’]ke do not try to make every Hunt fair$p$, $t$The Tjau'ke do not try to make every Hunt fair. They try to make it meaningful. The prey must be worth choosing. It must come to know, before the end, that it has become prey. And the hunter must willingly give up some part of their own advantage.$t$);

 -- 3. Synthetics can earn respect without becoming huntable.
 doc_text := pg_temp.swap(doc_text, $p$The Tjau['’]ke do not judge entire species$p$, $t$The Tjau'ke do not measure entire species. They measure the individual, among the prey the Honor Code allows. A weaker opponent can still prove worth choosing through planning, leadership, nerve, or simply by surviving again and again. An armed fool, meanwhile, may never interest them at all. Synthetics are a stranger case. A synthetic that shows genuine independence and judgment can earn a Tjau'ke's respect, even fascination, though the Honor Code does not permit it to be hunted. A hunter may admire one deeply and still have no right to its skull.$t$);

 perform set_config('app.change_reason', 'Aligned the Living Chronicle with the Honor Code', true);
 update public.library set body = doc_text where id = doc_id and body is distinct from doc_text;
end $migration$;

commit;
